<p>Add a text block and then add an optional translation</p>
<div id="html-with-translation-original">
    <?php echo $this->selectform; ?>
    <?php echo $this->htmlform; ?>
</div>
<div id="html-with-translation-templates-wrapper">
    <div class="html-with-translation-wrapper html-translation-templates">
        <div class="translations-grid translations-grid-templates">
            <div class="html-with-translation-select-template">
                <?php echo $this->languageSelectTemplate; ?>
            </div>
            <div class="html-with-translation-translation-template">
                <?php echo $this->translationTemplate; ?>
            </div>
            <div class="html-with-translation-remove"><button class="html-with-translation-remove-translation">Remove</button></div>
        </div>
    </div>
</div>
<a href="#" class="collapse" aria-label="collapse"><h4><?php echo $this->translate('Translations'); ?></h4></a>
<div class="collapsible">
    <button id="add-html-with-translation-translation"><?php echo $this->translate('Add a translation'); ?></button>
    <div id="html-with-translations" class="html-with-translation-wrapper">
        <?php foreach ($this->translations as $key => $translation): ?>
            <div class="translations-grid">
                <div><?php echo $translation_languages[$key]; ?></div>
                <div><?php echo $translation; ?></div>
                <div class="html-with-translation-remove"><button class="html-with-translation-remove-translation">Remove</button></div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
