<p>A Responsive Embed</p>
<?php echo $this->htmlform ?>
<div class="field">
    <div class="field-meta"><label for="aspect-select"><?php echo $this->translate('Aspect Ratio'); ?></label></div>
    <div class="inputs"><?php echo $this->aspectform ?></div>
</div>

<a href="#" class="collapse" aria-label="collapse"><h4><?php echo $this->translate('Region'); ?></h4></a>
<div class="collapsible">
    <?php echo $this->regionform ?>
</div>
